export const locationNames = [
  "Connaught Place",
  "Chandni Chowk",
  "Karol Bagh",
  "Dwarka",
  "Saket",
  "Vasant Kunj",
  "Lajpat Nagar",
  "Paharganj",
  "Nehru Place",
  "Rohini",
  "Pitampura",
  "Chanakyapuri",
  "Janakpuri",
  "South Extension",
  "Greater Kailash",
  "Laxmi Nagar",
  "Mayur Vihar",
  "Rajouri Garden",
  "Khan Market",
  "New Friends Colony",
  "Shahdara",
  "Shalimar Bagh",
  "Kalkaji",
  "Rajendra Place",
  "Malviya Nagar",
  "Mukherjee Nagar",
  "Kirti Nagar",
  "Model Town",
  "Patel Nagar",
  "Defence Colony",
  "Green Park",
  "Najafgarh",
  "Mehrauli",
  "Paschim Vihar",
  "Ashok Vihar",
  "Sarita Vihar",
  "Okhla",
  "Hauz Khas",
  "Jamia Nagar",
  "Safdarjung",
  "Govindpuri",
  "Jangpura",
  "Dilshad Garden",
  "Vikaspuri",
  "Vasundhara Enclave",
  "Shastri Nagar",
  "Sadar Bazaar",
  "Sultanpur",
  "Narela",
  "Punjabi Bagh",
  "Kamla Nagar",
  "Nizamuddin",
  "Jasola",
  "Sarai Rohilla",
  "Subhash Nagar",
  "Sarai Kale Khan",
  "Sarai Jullena",
  "Gulmohar Park",
  "Kondli",
  "Sarvodaya Enclave",
  "Nangloi",
  "Shakarpur",
  "Dhaula Kuan",
  "Badarpur",
  "Azadpur",
  "Hauz Rani",
  "Sarai Pipal Thala",
  "Khel Gaon",
  "Katwaria Sarai",
  "Naraina",
  "Rohini Sector 3",
  "Chawri Bazaar",
  "Kalkaji Extension",
  "Munirka",
  "Jangpura Extension",
  "Tughlaqabad",
  "Mandawali",
  "Kashmiri Gate",
  "Bawana",
  "Mangolpuri",
  "Tilak Nagar",
  "Majnu ka Tila",
  "Ramesh Nagar",
  "Shastri Park",
  "Shanti Niketan",
  "Dabri",
  "Kapashera",
  "Preet Vihar",
  "Maya Puri",
  "Uttam Nagar",
  "Rajokri",
  "Najafgarh Road Industrial Area",
  "Saraswati Vihar",
  "Shakur Basti",
  "Sarai Rohilla",
  "Pragati Maidan",
  "Tilak Marg",
  "Nirman Bhawan",
  "Gole Market",
  "North Avenue",
  "Moti Bagh",
  "Jor Bagh",
  "Sundar Nagar",
  "Nizamuddin East",
  "East of Kailash",
  "Kailash Colony",
  "CR Park",
  "Nehru Enclave",
  "Kalu Sarai",
  "Safdarjung Enclave",
  "Vasant Vihar",
  "Anand Niketan",
  "Arjun Nagar",
  "Bhikaji Cama Place",
  "Safdarjung Development Area",
  "Hauz Khaz Enclave",
  "Golf Links",
  "Prithviraj Road",
  "Jangpura Extension",
  "Sunder Nagar",
  "Panchsheel Enclave",
  "Shivalik Colony",
  "Sarvapriya Vihar",
  "Asiad Village",
  "Malcha Marg",
  "Shantipath",
  "Vinay Marg",
  "Chhatarpur",
  "Najafgarh Road",
  "Tagore Garden",
  "Adarsh Nagar",
  "Hudson Lane",
  "Vijay Nagar",
  "Pandav Nagar",
  "Ram Nagar",
  "Sadar Bazaar",
  "Daryaganj",
  "Barakhamba Road",
  "Bengali Market",
  "Bhagwan Das Road",
  "ITO",
  "Pusa Road",
  "Vikram Nagar",
  "Ganesh Nagar",
  "Maharani Bagh",
  "Hargovind Enclave",
  "Anand Lok",
  "Dayanand Colony",
  "Guru Angad Nagar",
  "Geeta Colony",
  "Anarkali Colony",
  "Gagan Vihar",
  "Anand Vihar",
  "Karkardooma",
  "Laxmi Nagar",
  "Nirman Vihar",
  "Preet Vihar",
  "Madhuban Enclave",
  "Dilshad Garden",
  "Gokalpur",
  "Old Seemapuri",
  "New Seemapuri",
  "Dilshad Colony",
  "Sahibabad",
  "Indirapuram",
  "Crossings Republik",
  "Shipra Suncity",
  "Vaishali",
  "Ghaziabad",
  "Noida",
  "Greater Noida",
  "Golf Course",
  "Greater Noida West",
  "Noida Extension",
  "Yamuna Expressway",
  "Alpha Commercial Belt",
  "Gamma Commercial Belt",
  "Delta Commercial Belt",
  "Beta Commercial Belt",
  "Sigma Commercial Belt",
  "Zeta Commercial Belt",
  "Omega Commercial Belt",
  "Phi Commercial Belt",
  "Theta Commercial Belt",
  "Kappa Commercial Belt",
  "Lambda Commercial Belt",
  "Rho Commercial Belt",
  "Mu Commercial Belt",
  "Chi Commercial Belt",
  "Psi Commercial Belt",
  "Upsilon Commercial Belt",
  "Xi Commercial Belt",
  "Tau Commercial Belt",
  "Iota Commercial Belt",
  "Eta Commercial Belt",
  "Dwarka Expressway",
  "Sohna Road",
  "Golf Course Road",
  "MG Road",
  "Cyber City",
  "Sector 29",
  "Sohna",
  "Manesar",
  "Pataudi",
  "Badshahpur",
  "Kherki Daula",
];
